/**
 * Application route definitions.
 * Centralizing all routes eliminates magic strings and ensures link integrity.
 */
export const ROUTES = {
  HOME: '/',
  LE_CLUB: '/le-club',
  LE_CLUB_EQUIPEMENT: '/le-club/equipement',
  BOUTIQUE: '/boutique',
  TRACES: '/traces',
  CALENDRIER: '/calendrier',
  SONDAGE: '/sondage',
  SATURDAY_RIDE: '/saturday-ride',
  LEADERBOARD: '/leaderboard',
  MEMBERS: '/members',
  BLOG: '/blog',
  GALERIE: '/galerie',
  SECURITE: '/securite',
  REJOINDRRE: '/rejoindre',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/login/forgot-password',
  PROFILE: '/profile',
  PROFILE_PASS: '/profile/pass',
  CHECKOUT: '/checkout',
  ADMIN: {
    ROOT: '/admin',
    BLOG: '/admin/blog',
    BLOG_NEW: '/admin/blog/new',
    CARRE_VERT: '/admin/carre-vert',
    EQUIPEMENTS: '/admin/equipements',
    EVENTS: '/admin/events',
    EVENTS_NEW: '/admin/events/new',
    EVENTS_IMPORT: '/admin/events/import',
    GALERIE: '/admin/galerie',
    HERO: '/admin/hero',
    MEMBERS: '/admin/members',
    MEMBERS_PHOTOS: '/admin/members/photos',
    POINTAGE_EXPRESS: '/admin/pointage-express',
    PROSPECTS: '/admin/prospects',
    SETTINGS: '/admin/settings',
    SONDAGES: '/admin/sondages',
    SONDAGES_NEW: '/admin/sondages/new',
    SORTIES_ESSAI: '/admin/sorties-essai',
    STATISTICS: '/admin/statistics',
    TRACES: '/admin/traces',
    ADD_TRACE: '/admin/add-trace',
  },
  API: {
    UPLOAD: '/api/upload',
    ADMIN_ATTENDANCE: '/api/admin/attendance',
    CALENDAR_ICS: '/api/calendar/ics',
    CALENDAR_SUBSCRIBE_ICS: '/api/calendar/subscribe.ics',
    CRON_SYNC_LEADERBOARD: '/api/cron/sync-leaderboard',
  },
} as const;
